export const ADD_REPO_SUCCESS = 'ADD_REPO_SUCCESS'
export const ADD_REPO_FAILURE = 'ADD_REPO_FAILURE'
export const GET_REPO_LIST_SUCCESS = 'GET_REPO_LIST_SUCCESS'
export const GET_REPO_LIST_FAILURE = 'GET_REPO_LIST_FAILURE'
